name: Build and Push Docker Images to ECR

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Configure AWS CLI
        run: |
          aws configure set aws_access_key_id ASIA5QDRWUR42WTHPOZS
          aws configure set aws_secret_access_key 9VWJDMAWWKv+fyRG7hsarGpgu1ARkED4wRhruk6Z
          aws configure set default.region us-east-1

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          aws-access-key-id: ASIA5QDRWUR42WTHPOZS
          aws-secret-access-key: 9VWJDMAWWKv+fyRG7hsarGpgu1ARkED4wRhruk6Z
          aws-region: us-east-1

      - name: Extract Git SHA
        id: vars
        run: echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build, tag, and push Docker image for MySQL service
        run: |
          docker build -t ${{ secrets.ECR_REPOSITORY }}/my-mysql-service:$(git rev-parse --short HEAD) -f Dockerfile_mysql .
          docker push ${{ secrets.ECR_REPOSITORY }}/my-mysql-service:$(git rev-parse --short HEAD)

      - name: Build, tag, and push Docker image for the main service
        run: |
          docker build -t ${{ secrets.ECR_REPOSITORY }}/my-main-service:$(git rev-parse --short HEAD) -f Dockerfile .
          docker push ${{ secrets.ECR_REPOSITORY }}/my-main-service:$(git rev-parse --short HEAD)
