name: Build and Push Docker Images to ECR

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
# chk
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Configure AWS CLI
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set aws_session_token ${{ secrets.AWS_SESSION_TOKEN }}
          aws configure set default.region ${{ secrets.AWS_REGION }}
          
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}

      - name: Extract Git SHA
        id: vars
        run: echo "SHA=${{ github.sha }}" >> $GITHUB_ENV

      - name: Build, tag, and push Docker image for MySQL service
        run: |
          docker build -t ${{ secrets.ECR_REPOSITORY }}/my-mysql-service:${{ env.SHA }} -f Dockerfile_mysql .
          docker push ${{ secrets.ECR_REPOSITORY }}/my-mysql-service:${{ env.SHA }}

      - name: Build, tag, and push Docker image for the main service
        run: |
          docker build -t ${{ secrets.ECR_REPOSITORY }}/my-main-service:${{ env.SHA }} -f Dockerfile .
          docker push ${{ secrets.ECR_REPOSITORY }}/my-main-service:${{ env.SHA }}
