name: Build and Push Docker Images to ECR

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Print AWS Access Key ID
      run: echo "AWS Access Key ID:"

    - name: Print AWS Secret Access Key
      run: echo "AWS Secret Access Key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}"
      
    - name: Print AWS Region
      run: echo "AWS Region: ${{ secrets.AWS_REGION }}"

    - name: Install AWS CLI
      run: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install
        aws --version

    - name: Log in to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Extract Git SHA
      id: vars
      run: echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - name: Build, tag, and push Docker image for MySQL service
      run: |
        docker build -t ${{ secrets.ECR_REPOSITORY }}/my-mysql-service:${{ env.sha }} -f Dockerfile_mysql .
        docker push ${{ secrets.ECR_REPOSITORY }}/my-mysql-service:${{ env.sha }}

    - name: Build, tag, and push Docker image for the main service
      run: |
        docker build -t ${{ secrets.EC
