name: Build and Push Docker Images to ECR

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Configure AWS CLI
        run: |
          aws configure set default.aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set default.aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.aws_session_token ${{ secrets.AWS_SESSION_TOKEN }}
          aws configure set default.region ${{ secrets.AWS_REGION }}
          
      - name: login to ecr command
        run: aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 927951398009.dkr.ecr.us-east-1.amazonaws.com

      - name: build app
        run: docker build -t clo835assignment1 .

      - name: build mysql image
        run: docker build -t my_db -f Dockerfile_mysql .

      - name: tag app image
        run: docker tag clo835assignment1:latest 927951398009.dkr.ecr.us-east-1.amazonaws.com/clo835assignment1:latest

      - name: tag mysql image
        run: docker tag my_db:latest 927951398009.dkr.ecr.us-east-1.amazonaws.com/ashran_my_mysql:latest

      - name: push app image
        run: docker push 927951398009.dkr.ecr.us-east-1.amazonaws.com/clo835assignment1:latest

      - name: push mysql image
        run: docker push 927951398009.dkr.ecr.us-east-1.amazonaws.com/ashran_my_mysql:latest
