name: Build and Push Docker Images to ECR

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Extract Git SHA
      id: vars
      run: echo "::set-output name=sha::$(git rev-parse --short HEAD)"

    - name: Build and push Docker image for MySQL service
      run: |
        docker build -t my-mysql-service:${{ steps.vars.outputs.sha }} -f Dockerfile_mysql .
        docker tag my-mysql-service:${{ steps.vars.outputs.sha }} ${{ secrets.ECR_REPOSITORY }}/my-mysql-service:${{ steps.vars.outputs.sha }}
        docker push ${{ secrets.ECR_REPOSITORY }}/my-mysql-service:${{ steps.vars.outputs.sha }}

    - name: Build and push Docker image for the main service
      run: |
        docker build -t my-main-service:${{ steps.vars.outputs.sha }} -f Dockerfile .
        docker tag my-main-service:${{ steps.vars.outputs.sha }} ${{ secrets.ECR_REPOSITORY }}/my-main-service:${{ steps.vars.outputs.sha }}
        docker push ${{ secrets.ECR_REPOSITORY }}/my-main-service:${{ steps.vars.outputs.sha }}
