name: Build and Push Docker Images to ECR

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Extract Git SHA
      id: vars
      run: echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - name: Build and push Docker image for MySQL service
      run: |
        docker build -t my-mysql-service:${{ env.sha }} -f Dockerfile_mysql .
        docker tag my-mysql-service:${{ env.sha }} ${{ secrets.ECR_REPOSITORY }}/my-mysql-service:${{ env.sha }}
        docker push ${{ secrets.ECR_REPOSITORY }}/my-mysql-service:${{ env.sha }}

    - name: Build and push Docker image for the main service
      run: |
        docker build -t my-main-service:${{ env.sha }} -f Dockerfile .
        docker tag my-main-service:${{ env.sha }} ${{ secrets.ECR_REPOSITORY }}/my-main-service:${{ env.sha }}
        docker push ${{ secrets.ECR_REPOSITORY }}/my-main-service:${{ env.sha }}
